#!/bin/bash

# Local Archive Generation Test Script
# This script simulates the GitHub Actions archive generation workflow

set -e  # Exit on any error

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
NC='\033[0m' # No Color

print_step() {
    echo -e "${BLUE}📋 Step: $1${NC}"
}

print_success() {
    echo -e "${GREEN}✅ $1${NC}"
}

print_warning() {
    echo -e "${YELLOW}⚠️  $1${NC}"
}

print_error() {
    echo -e "${RED}❌ $1${NC}"
}

print_info() {
    echo -e "${PURPLE}ℹ️  $1${NC}"
}

echo "🚀 FakeGen Archive Generation Test"
echo "=================================="

# Configuration
ARCHIVE_NAME="${1:-fakegen-samples-local}"
TIMESTAMP=$(date -u +"%Y%m%d-%H%M%S")
FULL_ARCHIVE_NAME="${ARCHIVE_NAME}-${TIMESTAMP}"
COMPRESSION_LEVEL="6"
INCLUDE_METADATA="true"

print_info "Archive name: $FULL_ARCHIVE_NAME"
print_info "Compression level: $COMPRESSION_LEVEL"
print_info "Include metadata: $INCLUDE_METADATA"

# Step 1: Setup validation
print_step "Setup validation"
if [ ! -f "package.json" ]; then
    print_error "package.json not found. Run this script from the project root."
    exit 1
fi
print_success "Package.json found"

if [ ! -f "bin/fakegen.js" ]; then
    print_error "bin/fakegen.js not found"
    exit 1
fi
print_success "FakeGen executable found"

# Step 2: Dependencies check
print_step "Dependencies check"
if [ ! -d "node_modules" ]; then
    print_warning "Node modules not found, installing dependencies..."
    npm install
fi
print_success "Dependencies available"

# Step 3: Clean previous artifacts
print_step "Cleaning previous artifacts"
if [ -d "fakegen" ]; then
    rm -rf fakegen/
    print_success "Cleaned previous fakegen directory"
fi

if [ -f "${FULL_ARCHIVE_NAME}.zip" ]; then
    rm -f "${FULL_ARCHIVE_NAME}.zip"
    print_success "Cleaned previous ZIP archive"
fi

if [ -f "${FULL_ARCHIVE_NAME}.tar.gz" ]; then
    rm -f "${FULL_ARCHIVE_NAME}.tar.gz"
    print_success "Cleaned previous TAR.GZ archive"
fi

# Step 4: Generate content
print_step "Generating FakeGen content"
npm run start > /tmp/fakegen_archive_test.log 2>&1
if [ $? -ne 0 ]; then
    print_error "FakeGen failed to run"
    cat /tmp/fakegen_archive_test.log
    exit 1
fi
print_success "FakeGen content generated successfully"

# Step 5: Verify generation
print_step "Verifying generated content"
if [ ! -d "fakegen" ]; then
    print_error "FakeGen directory not found!"
    exit 1
fi
print_success "FakeGen directory exists"

# Check key directories
for dir in data images favicon programming-code audio video; do
    if [ ! -d "fakegen/$dir" ]; then
        print_warning "$dir directory not found"
    else
        print_success "$dir directory exists"
    fi
done

# Step 6: Generate statistics
print_step "Generating content statistics"

TOTAL_FILES=$(find fakegen -type f | wc -l)
PROGRAMMING_FILES=$(find fakegen/programming-code -type f 2>/dev/null | wc -l || echo "0")
DATA_FILES=$(find fakegen/data -type f 2>/dev/null | wc -l || echo "0")
IMAGE_FILES=$(find fakegen/images -type f 2>/dev/null | wc -l || echo "0")
FAVICON_FILES=$(find fakegen/favicon -type f 2>/dev/null | wc -l || echo "0")
AUDIO_FILES=$(find fakegen/audio -type f 2>/dev/null | wc -l || echo "0")
VIDEO_FILES=$(find fakegen/video -type f 2>/dev/null | wc -l || echo "0")
TOTAL_SIZE=$(du -sh fakegen | cut -f1)

echo "📊 Content Statistics:"
echo "  - Total files: ${TOTAL_FILES}"
echo "  - Programming code files: ${PROGRAMMING_FILES}"
echo "  - Data files: ${DATA_FILES}"
echo "  - Image files: ${IMAGE_FILES}"
echo "  - Favicon files: ${FAVICON_FILES}"
echo "  - Audio files: ${AUDIO_FILES}"
echo "  - Video files: ${VIDEO_FILES}"
echo "  - Total size: ${TOTAL_SIZE}"

# Step 7: Create metadata
if [ "$INCLUDE_METADATA" = "true" ]; then
    print_step "Creating generation metadata"
    
    cat > fakegen/GENERATION_INFO.md << EOF
# FakeGen Content Archive (Local Test)

## Generation Information
- **Generated on**: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
- **FakeGen Version**: $(node -p "require('./package.json').version" 2>/dev/null || echo "Unknown")
- **Node.js Version**: $(node --version)
- **Platform**: $(uname -s) $(uname -r)
- **Architecture**: $(uname -m)
- **Generated by**: Local test script

## Content Statistics
- **Total Files**: ${TOTAL_FILES}
- **Programming Code Files**: ${PROGRAMMING_FILES}
- **Data Files**: ${DATA_FILES}
- **Image Files**: ${IMAGE_FILES}
- **Favicon Files**: ${FAVICON_FILES}
- **Audio Files**: ${AUDIO_FILES}
- **Video Files**: ${VIDEO_FILES}
- **Total Size**: ${TOTAL_SIZE}

## Directory Structure
\`\`\`
$(find fakegen -type d | head -20 | sort)
\`\`\`

## Programming Languages Generated
\`\`\`
$(ls fakegen/programming-code/ 2>/dev/null | grep -o '\.[^.]*$' | sort | uniq -c | sort -nr | head -10 || echo "No programming files found")
\`\`\`

## Data Formats Generated
\`\`\`
$(find fakegen/data -name "*.json" -o -name "*.csv" -o -name "*.xml" -o -name "*.yml" -o -name "*.toml" -o -name "*.txt" 2>/dev/null | grep -o '\.[^.]*$' | sort | uniq -c | sort -nr || echo "No data files found")
\`\`\`

## Image Formats
\`\`\`
$(find fakegen/images -name "*.jpg" -o -name "*.png" -o -name "*.webp" -o -name "*.svg" 2>/dev/null | grep -o '\.[^.]*$' | sort | uniq -c | sort -nr || echo "No image files found")
\`\`\`

## Usage
This archive contains sample output from FakeGen CLI tool for testing and demonstration purposes.
EOF

    print_success "Generation metadata created"
fi

# Step 8: Create file listing
print_step "Creating comprehensive file listing"

cat > fakegen/FILE_LISTING.txt << EOF
FakeGen Archive File Listing (Local Test)
Generated: $(date -u +"%Y-%m-%d %H:%M:%S UTC")

$(find fakegen -type f -not -name "FILE_LISTING.txt" -not -name "GENERATION_INFO.md" | sort)
EOF

print_success "File listing created"

# Step 9: Create sample showcase
print_step "Creating sample showcase"
mkdir -p fakegen/samples

# Copy sample files
if [ -f "fakegen/programming-code/hello_1.js" ]; then
    cp "fakegen/programming-code/hello_1.js" "fakegen/samples/sample.js"
    print_success "JavaScript sample copied"
fi

if [ -f "fakegen/programming-code/hello_1.py" ]; then
    cp "fakegen/programming-code/hello_1.py" "fakegen/samples/sample.py"
    print_success "Python sample copied"
fi

if [ -f "fakegen/data/user-profiles/json/user-profiles.json" ]; then
    head -20 "fakegen/data/user-profiles/json/user-profiles.json" > "fakegen/samples/user-profiles-preview.json"
    print_success "User profiles preview created"
fi

# Create samples README
cat > fakegen/samples/README.md << EOF
# Sample Files

This directory contains a few sample files for quick preview:

$(ls -la fakegen/samples/ | grep -v "^total" | grep -v "README.md")

For complete content, explore the main directories.
EOF

print_success "Sample showcase created"

# Step 10: Create archives
print_step "Creating ZIP archive"
if command -v zip >/dev/null 2>&1; then
    zip -r -$COMPRESSION_LEVEL "${FULL_ARCHIVE_NAME}.zip" fakegen/ > /dev/null
    ZIP_SIZE=$(du -sh "${FULL_ARCHIVE_NAME}.zip" | cut -f1)
    print_success "ZIP archive created: ${FULL_ARCHIVE_NAME}.zip (${ZIP_SIZE})"
else
    print_warning "zip command not found, skipping ZIP archive"
fi

print_step "Creating TAR.GZ archive"
if command -v tar >/dev/null 2>&1; then
    tar -czf "${FULL_ARCHIVE_NAME}.tar.gz" fakegen/
    TAR_SIZE=$(du -sh "${FULL_ARCHIVE_NAME}.tar.gz" | cut -f1)
    print_success "TAR.GZ archive created: ${FULL_ARCHIVE_NAME}.tar.gz (${TAR_SIZE})"
else
    print_warning "tar command not found, skipping TAR.GZ archive"
fi

# Step 11: Verify archives
print_step "Verifying created archives"

if [ -f "${FULL_ARCHIVE_NAME}.zip" ]; then
    echo "📦 ZIP Archive:"
    ls -lh "${FULL_ARCHIVE_NAME}.zip"
    if command -v unzip >/dev/null 2>&1; then
        FILE_COUNT=$(unzip -l "${FULL_ARCHIVE_NAME}.zip" | tail -1 | awk '{print $2}')
        echo "   Contents: ${FILE_COUNT} files"
    fi
fi

if [ -f "${FULL_ARCHIVE_NAME}.tar.gz" ]; then
    echo "📦 TAR.GZ Archive:"
    ls -lh "${FULL_ARCHIVE_NAME}.tar.gz"
    if command -v tar >/dev/null 2>&1; then
        FILE_COUNT=$(tar -tzf "${FULL_ARCHIVE_NAME}.tar.gz" | wc -l)
        echo "   Contents: ${FILE_COUNT} files"
    fi
fi

# Step 12: Show sample content
print_step "Displaying sample content"

if [ -f "fakegen/samples/sample.js" ]; then
    echo "📝 Sample JavaScript code:"
    echo "--- fakegen/samples/sample.js ---"
    cat "fakegen/samples/sample.js"
    echo "---"
fi

if [ -f "fakegen/samples/sample.py" ]; then
    echo "📝 Sample Python code:"
    echo "--- fakegen/samples/sample.py ---"
    cat "fakegen/samples/sample.py"
    echo "---"
fi

# Step 13: Final summary
echo ""
echo "🎉 Archive Generation Test COMPLETED SUCCESSFULLY!"
echo "=================================================="
echo ""
echo "Summary:"
echo "✅ Content generated successfully"
echo "✅ Archives created successfully"
echo "✅ Metadata and samples included"
echo ""
echo "Generated files:"
if [ -f "${FULL_ARCHIVE_NAME}.zip" ]; then
    echo "  📦 ${FULL_ARCHIVE_NAME}.zip"
fi
if [ -f "${FULL_ARCHIVE_NAME}.tar.gz" ]; then
    echo "  📦 ${FULL_ARCHIVE_NAME}.tar.gz"
fi
echo "  📁 fakegen/ directory"
echo ""
echo "Statistics:"
echo "  📊 Total files: ${TOTAL_FILES}"
echo "  💾 Content size: ${TOTAL_SIZE}"
echo ""
echo "Next steps:"
echo "1. Test the archives by extracting them"
echo "2. Verify the GitHub Actions workflow"
echo "3. Run the workflow manually to test in CI/CD environment"

# Cleanup log file
rm -f /tmp/fakegen_archive_test.log

print_success "Archive generation test completed!"